--1 A
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SELECT * FROM Buku
WHERE Id_Buku='B6'

--1 B
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SELECT * FROM Buku
WHERE Id_Buku='B6'

--2 A
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	SELECT * FROM Buku
	WHERE Id_Buku='B6'

	WAITFOR DELAY '00:00:10'

	SELECT * FROM Buku
	WHERE Id_Buku='B6'
COMMIT TRAN


--2 B
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	SELECT * FROM Buku
	WHERE Id_Buku='B6'

	WAITFOR DELAY '00:00:10'

	SELECT * FROM Buku
	WHERE Id_Buku='B6'
COMMIT TRAN

--3 A
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	SELECT * FROM Buku
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Buku

COMMIT TRAN

--3 B
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	SELECT * FROM Buku
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Buku

COMMIT TRAN